repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        # Pre-commit does some static analysis by caching packages (can
        # be found in ~/.cache/pre-commit/). When used in a virtualenv
        # (like pyenv), flake8 does not work correctly withthe default
        # language and the custom dnode match linter breaks.
        # To get around this, pre-commit devs recommend to use it as a
        # "system" hook (default is "local"). See
        # https://github.com/pre-commit/pre-commit-hooks/issues/157
        # for more information on this issue.
        language: system

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # TODO: This throws an error on MacOS Big Sur. Updating the rev
    # to v3.3.0 does not fix the problem either. Here is the error for
    # reference:
    #
    #   could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
    #
    # -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
